name: Tests

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      XDG_RUNTIME_DIR: "${{ runner.temp }}/edgedb"
    strategy:
      matrix:
        node-version: ["14"]
        os: [ubuntu-latest]
        edgedb-version: ["stable"]

        include:
          - os: macos-latest
            node-version: "14"
            edgedb-version: "stable"

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install EdgeDB
        uses: edgedb/setup-edgedb@v1
        with:
          server-version: ${{ matrix.edgedb-version }}

      - name: Install deps
        run: |
          npm ci

      - name: Init edgedb project and run migrations
          edgedb project init --non-interactive
          npm run test:migrate

      - name: Build the project
        run: |
          npm run build
      - name: Run Tests
        run: |
          npm run test