name: Tests

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["14"]
        os: [ubuntu-latest]
        edgedb-version: ["stable"]

        include:
          - os: macos-latest
            node-version: "14"
            edgedb-version: "stable"
          # - os: windows-latest
          #   node-version: "14"
          #   edgedb-version: "stable"

    steps:
      # - name: Setup WSL
      #   if: ${{ matrix.os == 'windows-latest' }}
      #   uses: vampire/setup-wsl@v1
      #   with:
      #     wsl-shell-user: edgedb
      #     additional-packages:
      #       ca-certificates
      #       curl

      - uses: actions/checkout@v1
        with:
          fetch-depth: 50

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Set up Deno
      #   uses: denoland/setup-deno@v1
      #   with:
      #     deno-version: v1.12.x

      - name: Install EdgeDB
        uses: edgedb/setup-edgedb@v1
        with:
          server-version: ${{ matrix.edgedb-version }}

      - name: Install deps
        run: |
          npm ci
      - name: Build the project
        run: |
          npm run build
      - name: Run Tests
        run: |
          npm run test